services:
  db:
    image: postgres:17.6-trixie@sha256:e6a4209d1a4893f2df3bdcde58f8926c3c929c4d51df90990ed1b36d83c1382a
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
      POSTGRES_DB: ${POSTGRES_DB:-pomodoro}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: