services:
  db:
    image: postgres:17.6-trixie@sha256:e6a4209d1a4893f2df3bdcde58f8926c3c929c4d51df90990ed1b36d83c1382a
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
      POSTGRES_DB: ${POSTGRES_DB:-pomodoro}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    networks:
      - backend

  migrations:
    image: flyway/flyway:11.14-alpine@sha256:6bc960b4221686ce4bb57130bcd5439a909eb1360457b2a741dae3c877f1d6ef
    depends_on:
      db:
        condition: service_healthy
    command: [
      "migrate",
      "-X"
    ]
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-pomodoro}
      FLYWAY_USER: ${POSTGRES_USER:?required}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:?required}
      FLYWAY_CONNECT_RETRIES: "60"
      FLYWAY_DEFAULT_SCHEMA: public
    volumes:
      - ./migrations:/flyway/sql:ro
    networks:
      - backend

  api:
    build:
      context: ./api
    env_file:
      - ./api.env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-pomodoro}"
      API_PORT: ${API_PORT:-3000}
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./api:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 5s
    networks:
      - backend
      - web
    ports:
      - "3000:3000" # Note pour plus tard: A supprimer pour la prod

  frontend:
    build:
      context: ./frontend
    env_file: ./frontend.env
    depends_on: 
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
     - "5173:5173"
    networks:
      - web

volumes:
  pg_data:

networks:
  backend:
    internal: true
  web:
    driver: bridge